# Generated by Django 4.1.3 on 2024-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('parentname', models.CharField(blank=True, max_length=100, null=True)),
                ('className', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
